Fix redirects
OpenMS/OpenMS-website pull request #116
Opened 2023-08-15 11:36 UTC by matteopilz

#### Brief description of what is fixed or changed

2023-08-15 14:29 UTC, jpfeuffer commented
Probably there was never a separate page for it. Just an overview on the application overview page. But that is not how it was intended, so I changed it.
You could copy the contents of the FlashIDA section of the applications.md.bup file into a separate flashida.md file in the application folder.

2023-08-16 06:48 UTC, jpfeuffer requested changes

2023-08-16 06:48 UTC, jpfeuffer commented on content/en/applications/flashida.md
> +title: FLASHIca
```suggestion
title: FLASHIda
```

2023-08-16 06:48 UTC, jpfeuffer commented on static/_redirects
>  /FLASHIda /applications/#intelligent-data-acquisition-for-top-down-proteomics-flashida 200
This line and the following must be changed, too.

2023-08-17 05:35 UTC, matteopilz commented on static/_redirects
>  /FLASHIda /applications/#intelligent-data-acquisition-for-top-down-proteomics-flashida 200
To what?

2023-08-17 14:23 UTC, jpfeuffer commented on static/_redirects
>  /FLASHIda /applications/#intelligent-data-acquisition-for-top-down-proteomics-flashida 200
/applications/nameofyournewfile.md

I guess /applications/flashida

2023-09-07 11:25 UTC, cbielow commented
ready for merge @matteopilz  @jpfeuffer ?

2023-09-07 11:31 UTC, jpfeuffer commented
No, see unresolved comments.

2023-09-07 17:07 UTC, jpfeuffer approved these changes

2023-09-07 17:07 UTC, merged