General Remarks
OpenMS/OpenMS-website pull request #66
Opened 2022-12-19 08:43 UTC by matteopilz

#### Brief description of what is fixed or changed

2023-03-09 07:46 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Execute python bindings
bindings are not executed
```suggestion
    - title: Use OpenMS in python
```

2023-03-09 07:57 UTC, matteopilz commented
@tjeerdijk, can you take a look, so we can wrap this up? I think you had some concerns with using the image of all workflow logos. @rahul799, did you take a look if we can put h1 level headers in the sidebar as well?

2023-03-09 09:17 UTC, timosachsenberg commented
@jpfeuffer do you know if we can use these logos (e.g., mainly KNIME seems to be picky)?

2023-03-09 09:48 UTC, matteopilz commented
Not a lawyer, but I would say that we can.
https://de.wikipedia.org/wiki/Datei:KNIMELogoTM.svg
https://galaxyproject.org/images/galaxy-logos/
https://github.com/nextflow-io/trademark
https://nf-co.re/developers/design_guidelines

2023-03-10 11:38 UTC, jpfeuffer commented
Can't we insert separate logos, so we could actually reuse them in other places?
Also updating would be much easier!

2023-03-20 14:02 UTC, poshul commented
@tjeerdijk would you have a chance to take a look at this today?

2023-04-17 06:36 UTC, matteopilz commented
@jpfeuffer, can you check if everything is correct?

2023-04-25 06:53 UTC, timosachsenberg commented
@jpfeuffer can you give it a quick look? screenshots wotj errors are already creeping into the paper :P

2023-04-25 06:54 UTC, timosachsenberg commented on content/en/about.md
> +OpenMS is a free open-source software C++ library for LC-MS data management and analyses. It offers an infrastructure for rapid development of mass spectrometry related software. OpenMS is available
```suggestion
OpenMS is an open-source software C++ library for LC-MS data management and analyses. It offers an infrastructure for rapid development of mass spectrometry related software. OpenMS is available under a modified three clause [BSD license](https://github.com/openms/openms/blob/main/License.txt) and runs under Windows, macOS, and Linux.
```

2023-04-25 06:56 UTC, timosachsenberg commented on content/en/communication.md
> +### <a class="button cta rounded primary-btn raised" href="https://github.com/openms">GitHub</a>
```suggestion
### <a class="button cta rounded primary-btn raised" href="https://github.com/OpenMS">GitHub</a>
```

2023-04-25 06:56 UTC, timosachsenberg commented on content/en/communication.md
> +### <a class="button cta rounded primary-btn raised" href="https://github.com/openms">GitHub</a>
works also in lower case as it seems

2023-04-25 06:59 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
```suggestion
    - title: Run existing workflows
```

2023-04-25 07:04 UTC, timosachsenberg commented on themes/scientific-python-hugo-theme
what about these files?

2023-04-25 07:24 UTC, jpfeuffer requested changes

2023-04-25 07:24 UTC, jpfeuffer commented on content/en/communication.md
> +These lists are the main form of receiving OpenMS related updates, like new features, changes to the roadmap, and all kinds of project-wide decision making.
```suggestion
These lists are the main form of receiving OpenMS-related updates, like new features, changes to the roadmap, and all kinds of project-wide decision making.
```

2023-04-25 07:24 UTC, jpfeuffer commented on content/en/tutorials.md
> +We will release new versions on our [GitHub page for Tutorials](https://github.com/OpenMS/Tutorials/releases). Older versions can be found there. It also contains releases for the versions used in di
Not sure if I would link to releases. If so, we really need to make sure to create releases, not just tag the repo.

2023-04-25 07:29 UTC, jpfeuffer requested changes

2023-04-25 07:29 UTC, jpfeuffer commented on content/en/config.yaml
> +      buttonLink: "https://openms.readthedocs.io/en/latest/run-workflows-with-openms-tools/openms-in-knime.html"
This does not exist anymore.

2023-04-25 07:45 UTC, timosachsenberg commented on content/en/tutorials.md
> +We will release new versions on our [GitHub page for Tutorials](https://github.com/OpenMS/Tutorials/releases). Older versions can be found there. It also contains releases for the versions used in di
k let's keep this low maintenance and let's not link to releases

2023-04-25 08:09 UTC, matteopilz commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
The idea here was to have some kind of hierarchy in difficulty. KNIME workflows are / should be the most basic use case of OpenMS.

2023-04-25 08:50 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
not if we have web apps :P

2023-04-25 08:52 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
I just find it a bit redundant to have it in the title. Another reason: the acronyme KNIME doesn't add information to beginners so we can leave it out in the title (but still have it in the subtitle).

2023-04-25 09:58 UTC, matteopilz commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
We need to restructure the website anyways, there is still a lot out of order or unintuitive. Question is, should we do this later or merge these changes first. The link and reference to workflows in general is in create your own workflows, one step later.

2023-04-25 10:00 UTC, matteopilz commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
We wanted to have some distinction between this step and the next.

2023-04-25 10:08 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
I just wanted to chang the title not the subtitle. It still refers to knime so we still have the distinction.

2023-04-25 10:09 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
I just wanted to chang the title not the subtitle. It still refers to knime so we still have the distinction.

2023-04-25 10:25 UTC, jpfeuffer commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
The problem is, the way our docs are currently structured the workflow system is on the top-level.
So there will not be an "existing workflows" overview page for all workflow systems. The alternative
is to restructure the docs by topic and on every page have a distinction between the workflow systems.
Also not great at all. So I think just silently picking KNIME here is fine.

But: I am not sure if a super new user knows what to do on the KNIME hub if KNIME was not even introduced yet.

So maybe the restructure is really necessary.

Just saying: We are discussing this for the fifth time or so. How about making a final decision in a larger meeting? There is always someone coming up who doesn't like a certain part but it is probably not possible to satisfy every concern.

2023-04-25 10:34 UTC, matteopilz commented on content/en/config.yaml
>            link: /install
Just noticed, that we have one navigation bar install link and two extra on the main page.

2023-04-25 10:45 UTC, timosachsenberg commented on content/en/config.yaml
> +    - title: Run existing workflows with KNIME
good point - this is turning into turning into bike shedding 
I commited and resolved this issue.

2023-04-25 11:35 UTC, matteopilz commented on content/en/tutorials.md
> +### Proteomics & Metabolomics Background Material
Maybe it's best then to remove the tutorials page or link to the documentation again (better just remove it though).

2023-04-25 11:36 UTC, matteopilz commented on themes/scientific-python-hugo-theme
Those are just changed formatting, which I think looks slightly better.

2023-04-25 11:44 UTC, timosachsenberg commented on content/en/tutorials.md
> +### Proteomics & Metabolomics Background Material
k can you double check that information is available in the documentation and then remove it? @jpfeuffer any concerns removing it?

2023-04-26 12:30 UTC, matteopilz commented
Ok, removed it.

2023-04-26 13:26 UTC, timosachsenberg commented
just checked the deployment link... seems install link on the top links to nowhere https://openms.readthedocs.io/en/latest/openms-applications-and-tools/installation.html

2023-04-26 13:36 UTC, matteopilz commented
> just checked the deployment link... seems install link on the top links to nowhere https://openms.readthedocs.io/en/latest/openms-applications-and-tools/installation.html

Not yet, the changes are connected to Julianus' restructure https://github.com/OpenMS/OpenMS-docs/pull/198

2023-04-27 07:13 UTC, timosachsenberg commented
link now working?

2023-04-27 08:55 UTC, timosachsenberg approved these changes

2023-04-27 08:57 UTC, timosachsenberg commented
@jpfeuffer merge?

2023-04-27 09:28 UTC, jpfeuffer approved these changes

2023-04-27 09:28 UTC, merged

2023-04-27 09:31 UTC, timosachsenberg commented
Nice!